"""empty message

Revision ID: 811c0ed166c8
Revises: a7c7f3b11b3b
Create Date: 2022-09-19 11:08:21.847180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811c0ed166c8'
down_revision = 'a7c7f3b11b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('rif', sa.String(length=11), nullable=False),
    sa.Column('sicm', sa.Integer(), nullable=True, secundary_key=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rif')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    # ### end Alembic commands ###
