"""empty message

Revision ID: 8910b5d243b0
Revises: cff0c775f850
Create Date: 2022-09-27 17:05:12.623363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8910b5d243b0'
down_revision = 'cff0c775f850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
