"""empty message

Revision ID: a7c7f3b11b3b
Revises: b2fc6b7ae7e8
Create Date: 2022-09-14 17:55:06.434615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c7f3b11b3b'
down_revision = 'b2fc6b7ae7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rif', sa.String(length=11), nullable=False))
    op.add_column('user', sa.Column('sicm', sa.Integer(), nullable=True, secundary_key=True))
    op.create_unique_constraint(None, 'user', ['rif'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'sicm')
    op.drop_column('user', 'rif')
    # ### end Alembic commands ###
