"""empty message

Revision ID: c21e79317372
Revises: 811c0ed166c8
Create Date: 2022-09-26 04:26:40.341870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21e79317372'
down_revision = '811c0ed166c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'sicm',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('login', 'sicm',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
