"""empty message

Revision ID: cff0c775f850
Revises: c21e79317372
Create Date: 2022-09-27 17:02:10.480935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff0c775f850'
down_revision = 'c21e79317372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    op.create_unique_constraint(None, 'user', ['sicm'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_table('login',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rif', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('sicm', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='login_pkey'),
    sa.UniqueConstraint('email', name='login_email_key'),
    sa.UniqueConstraint('rif', name='login_rif_key')
    )
    # ### end Alembic commands ###
