"""empty message

Revision ID: d76763d46ff6
Revises: e157624ec889
Create Date: 2022-09-16 20:01:36.375705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76763d46ff6'
down_revision = 'e157624ec889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('url_image', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'url_image')
    # ### end Alembic commands ###
